// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: csm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterCacheServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerSpec string `protobuf:"bytes,1,opt,name=server_spec,json=serverSpec,proto3" json:"server_spec,omitempty"`
	Shard      int64  `protobuf:"varint,2,opt,name=shard,proto3" json:"shard,omitempty"`
}

func (x *RegisterCacheServerRequest) Reset() {
	*x = RegisterCacheServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCacheServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCacheServerRequest) ProtoMessage() {}

func (x *RegisterCacheServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCacheServerRequest.ProtoReflect.Descriptor instead.
func (*RegisterCacheServerRequest) Descriptor() ([]byte, []int) {
	return file_csm_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterCacheServerRequest) GetServerSpec() string {
	if x != nil {
		return x.ServerSpec
	}
	return ""
}

func (x *RegisterCacheServerRequest) GetShard() int64 {
	if x != nil {
		return x.Shard
	}
	return 0
}

type RegisterCacheServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegisteredPath string `protobuf:"bytes,1,opt,name=registered_path,json=registeredPath,proto3" json:"registered_path,omitempty"`
}

func (x *RegisterCacheServerResponse) Reset() {
	*x = RegisterCacheServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCacheServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCacheServerResponse) ProtoMessage() {}

func (x *RegisterCacheServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCacheServerResponse.ProtoReflect.Descriptor instead.
func (*RegisterCacheServerResponse) Descriptor() ([]byte, []int) {
	return file_csm_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterCacheServerResponse) GetRegisteredPath() string {
	if x != nil {
		return x.RegisteredPath
	}
	return ""
}

var File_csm_proto protoreflect.FileDescriptor

var file_csm_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x61, 0x6e,
	0x61, 0x63, 0x68, 0x65, 0x2e, 0x63, 0x73, 0x6d, 0x22, 0x53, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x22, 0x46, 0x0a,
	0x1b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65,
	0x64, 0x50, 0x61, 0x74, 0x68, 0x32, 0x7a, 0x0a, 0x0c, 0x53, 0x68, 0x61, 0x72, 0x64, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x6a, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x27, 0x2e, 0x67,
	0x61, 0x6e, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x63, 0x73, 0x6d, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x67, 0x61, 0x6e, 0x61, 0x63, 0x68, 0x65, 0x2e,
	0x63, 0x73, 0x6d, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x6c, 0x74, 0x68, 0x6b, 0x2f, 0x67, 0x61, 0x6e, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x63, 0x73,
	0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_csm_proto_rawDescOnce sync.Once
	file_csm_proto_rawDescData = file_csm_proto_rawDesc
)

func file_csm_proto_rawDescGZIP() []byte {
	file_csm_proto_rawDescOnce.Do(func() {
		file_csm_proto_rawDescData = protoimpl.X.CompressGZIP(file_csm_proto_rawDescData)
	})
	return file_csm_proto_rawDescData
}

var file_csm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_csm_proto_goTypes = []interface{}{
	(*RegisterCacheServerRequest)(nil),  // 0: ganache.csm.RegisterCacheServerRequest
	(*RegisterCacheServerResponse)(nil), // 1: ganache.csm.RegisterCacheServerResponse
}
var file_csm_proto_depIdxs = []int32{
	0, // 0: ganache.csm.ShardManager.RegisterCacheServer:input_type -> ganache.csm.RegisterCacheServerRequest
	1, // 1: ganache.csm.ShardManager.RegisterCacheServer:output_type -> ganache.csm.RegisterCacheServerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_csm_proto_init() }
func file_csm_proto_init() {
	if File_csm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_csm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCacheServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCacheServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_csm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_csm_proto_goTypes,
		DependencyIndexes: file_csm_proto_depIdxs,
		MessageInfos:      file_csm_proto_msgTypes,
	}.Build()
	File_csm_proto = out.File
	file_csm_proto_rawDesc = nil
	file_csm_proto_goTypes = nil
	file_csm_proto_depIdxs = nil
}
